#!/bin/bash
# This script will trim away 1 pixel border from given image. Required since bevy_ecs_ldtk or bevy_ecs_tilemap doesn't understand padding in spritesheet.

set -euo pipefail

die() {
    echo "$@" 1>&2
    exit 1
}

input="$1"
[ ! -f "$input" ] && die "file not found: '$input'"
base_dir="$(dirname "$input")"

filename="$(basename "$input")"
if ! grep -qF '.' <<< "$filename"; then
    ext=""
else
    ext=".${filename##*.}"
fi
filename="${filename%.*}"
output="$base_dir/${filename}.export${ext}"

convert "$input" -shave 1x1 "$output"
echo "$output"
